package com.delarosa.portal;

import javafx.embed.swing.JFXPanel;

/**
 *
 * @author odelarosa
 */
public class Browser extends javax.swing.JFrame {

    /**
     * Creates new form Browser
     * @param jfxPanel
     */
    public Browser(JFXPanel jfxPanel) {
        initComponents();

        getContentPane().add(jfxPanel);

        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ZkPortal");
        getContentPane().setLayout(new java.awt.GridLayout());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
